openapi: 3.2.0
info:
  title: Fenergo Nebula Integration Core Tasks API
  description: '**Integration Core API**:


    Integration Core BFF API allows to create and access integration flows and its'' executions.'
  version: '1.0'
servers:
- url: /integrationcore
security:
- Bearer: []
tags:
- name: Tasks
paths:
  /api/task/internalApi/endpoints:
    get:
      tags:
      - Tasks
      summary: Gets InternalApi task endpoints
      description: 'Required permissions:

        Following permissions are required: IntegrationFlowsConfigurationAccess


        Required permissions:

        Following permissions are required: IntegrationFlowsConfigurationAccess'
      operationId: GetInternalApiEndpointsList
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalApiEndpointDtoIEnumerableServiceResponse'
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/task/internalApi/endpoints/{endpoint}:
    get:
      tags:
      - Tasks
      summary: Gets Internal Api Endpoint Sample Request
      description: 'Required permissions:

        Following permissions are required: IntegrationFlowsConfigurationAccess


        Required permissions:

        Following permissions are required: IntegrationFlowsConfigurationAccess'
      operationId: GetInternalApiEndpointConfiguration
      parameters:
      - name: endpoint
        in: path
        description: The internal API endpoint
        required: true
        schema:
          allOf:
          - $ref: '#/components/schemas/InternalApiEndpoint'
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalApiEndpointConfigurationDtoServiceResponse'
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    InternalApiEndpointDto:
      type: object
      properties:
        endpoint:
          allOf:
          - $ref: '#/components/schemas/InternalApiEndpoint'
        friendlyName:
          type:
          - string
          - 'null'
      additionalProperties: false
    InternalApiEndpointDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/InternalApiEndpointDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    InternalApiEndpointConfigurationDtoServiceResponse:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/InternalApiEndpointConfigurationDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    InternalApiEndpointConfigurationDto:
      type: object
      properties:
        sampleRequest: {}
      additionalProperties: false
    InternalApiEndpoint:
      enum:
      - GetJourneyInstanceById
      - CreateEntity
      - UpdateEntityDraft
      - LegalEntityIdentifierSearch
      - LegalEntityAdvancedSearch
      - CreateEntityDraft
      - ReopenTask
      - GetSignificanceResult
      - GetInternalEntityIdByExDataSubscriptionId
      - GetDocumentSignedUrl
      - GetDataSources
      type: string
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
