openapi: 3.2.0
info:
  title: Fenergo Nebula External Data Command Data & Docs Documents…
  description: '**External Data Command API**:


    External Data Command API allows to import information about clients, their associated parties, documents from external providers.'
  version: '1.0'
servers:
- url: /externaldatacommand
security:
- Bearer: []
tags:
- name: Data & Docs Documents
paths:
  /api/datadocs/saveDataDocsDocuments:
    post:
      tags:
      - Data & Docs Documents
      summary: Save Data&Doc Documents status
      description: 'This method will save Data&Doc Documents status.


        The method will return the status.


        Required permissions:

        Following permissions are required: ExternalDataAccess


        Required permissions:

        Following permissions are required: ExternalDataAccess'
      operationId: SaveDataDocsDocument
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Save Data&Doc Documents status
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DataDocsDocumentsStatusRequestDtoServiceRequest'
              description: Service request data
      responses:
        '202':
          description: Success. Save Data & Docs request created
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/datadocs/importDataDocsDocuments:
    post:
      tags:
      - Data & Docs Documents
      summary: Import Data&Doc documents
      description: 'This method will import Data&Doc documents.


        Required permissions:

        Following permissions are required: ExternalDataAccess


        Required permissions:

        Following permissions are required: ExternalDataAccess'
      operationId: ImportDataDocsDocuments
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Import Data&Doc documents
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DataDocsImportDtoServiceRequest'
              description: Service request data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataDocsDocumentImportResultsDtoServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '202':
          description: Success. Import Data & Docs request created
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    CreatedDocumentDto:
      type: object
      properties:
        success:
          type: boolean
        messages:
          type:
          - array
          - 'null'
          items:
            type: string
        id:
          type:
          - string
          - 'null'
        properties:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PublishEntityPropertyDto'
        publishType:
          type:
          - string
          - 'null'
        failedDependencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PublishedEntityDto'
        externalId:
          type:
          - string
          - 'null'
      additionalProperties: false
    DataDocsDocumentStatusRequestDto:
      required:
      - documentId
      - status
      type: object
      properties:
        documentId:
          type: string
          format: uuid
        status:
          allOf:
          - $ref: '#/components/schemas/DataDocsDocumentStatus'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DataDocsImportDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/DataDocsImportDto'
          description: The service request DTO
      additionalProperties: false
      description: Service request data
    DataDocsDocumentsStatusRequestDto:
      required:
      - documents
      - importRequestId
      - journeyId
      - taskId
      type: object
      properties:
        importRequestId:
          minLength: 1
          type: string
          format: uuid
        journeyId:
          minLength: 1
          type: string
          format: uuid
        taskId:
          minLength: 1
          type: string
          format: uuid
        documents:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/DataDocsDocumentStatusRequestDto'
      additionalProperties: false
    DataDocsDocumentImportResultsDtoServiceResponse:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/DataDocsDocumentImportResultsDto'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DataDocsImportDto:
      required:
      - journeyId
      - taskId
      type: object
      properties:
        taskId:
          minLength: 1
          type: string
          description: ID of the journey task
          format: uuid
          example: 300e2046-f78c-49d2-b326-afba28dc301c
        journeyId:
          minLength: 1
          type: string
          description: ID of the journey
          format: uuid
          example: 300e2046-f78c-49d2-b326-afba28dc301c
      additionalProperties: false
      description: DTO representing Data Docs Entity Details Request
    DataDocsDocumentImportResultsDto:
      type: object
      properties:
        documents:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CreatedDocumentDto'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    PublishEntityPropertyDto:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        value:
          type:
          - string
          - 'null'
      additionalProperties: false
    DataDocsDocumentsStatusRequestDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/DataDocsDocumentsStatusRequestDto'
          description: The service request DTO
      additionalProperties: false
      description: Service request data
    DataDocsDocumentStatus:
      enum:
      - Available
      - Initiated
      - Requested
      - Completed
      - Rejected
      - FailedInitiation
      - FailedRequest
      type: string
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    PublishedEntityDto:
      type: object
      properties:
        success:
          type: boolean
        messages:
          type:
          - array
          - 'null'
          items:
            type: string
        id:
          type:
          - string
          - 'null'
        properties:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PublishEntityPropertyDto'
        publishType:
          type:
          - string
          - 'null'
        failedDependencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PublishedEntityDto'
        externalId:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
