openapi: 3.2.0
info:
  title: Fenergo Nebula Business Metrics Query Task Daily Metrics API
  description: '**Business Metrics Query API**:


    Business Metrics Query API provides endpoints in order to retrieve all related models and their versions.


    **Business Metrics Query API provides**:'
  version: '1.0'
servers:
- url: /businessmetricsquery
security:
- Bearer: []
tags:
- name: TaskDailyMetrics
paths:
  /api/taskdailymetrics/gettaskdailymetricsbydaterange:
    post:
      tags:
      - TaskDailyMetrics
      summary: Get daily task metrics by date range
      description: 'Required permissions:

        Following permissions are required: BusinessMetricsAccess'
      operationId: GetTaskDailyMetricsByDateRange
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeRequestDtoServiceRequest'
          text/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeRequestDtoServiceRequest'
          application/*+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeRequestDtoServiceRequest'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeResponseDtoIEnumerableServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeResponseDtoIEnumerableServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeResponseDtoIEnumerableServiceResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '500':
          description: Internal Server Error
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    GetTaskDailyMetricsByDateRangeResponseDto:
      type: object
      properties:
        tenant:
          type:
          - string
          - 'null'
        taskType:
          type:
          - string
          - 'null'
        taskName:
          type:
          - string
          - 'null'
        average:
          type: number
          format: double
        date:
          type:
          - string
          - 'null'
        completedCount:
          type: integer
          format: int32
        automatedCount:
          type: integer
          format: int32
        reopenedCount:
          type: integer
          format: int32
      additionalProperties: false
    GetTaskDailyMetricsByDateRangeResponseDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeResponseDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    GetTaskDailyMetricsByDateRangeRequestDto:
      type: object
      properties:
        startDate:
          type:
          - string
          - 'null'
          description: Start Date for metrics
          example: 2023/04/24
        endDate:
          type:
          - string
          - 'null'
          description: End Date for metrics
          example: 2023/05/25
        numberOfRecordsToSkip:
          type:
          - integer
          - 'null'
          description: Number of records to skip, and not include in the response. If the value is undefined, no records will be skipped.
          format: int32
          example: 10
        recordLimit:
          type:
          - integer
          - 'null'
          description: Maximum amount of records to include in the response. If the value is undefined all records will be returned.
          format: int32
          example: 10
      additionalProperties: false
    GetTaskDailyMetricsByDateRangeRequestDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/GetTaskDailyMetricsByDateRangeRequestDto'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
