openapi: 3.2.0
info:
  title: Fenergo Nebula Data Protection Query Entity Check…
  description: '**Data Protection Query API**:


    Data Protection Query API provides endpoints in order to retrieve all related models and their versions.


    **Data Protection API provides**:


    The ability to query for Data Protection Regimes.'
  version: '1.0'
servers:
- url: /dataprotectionquery
security:
- Bearer: []
tags:
- name: EntityCheckVerification
paths:
  /api/entitycheckverification/{type}:
    get:
      tags:
      - EntityCheckVerification
      summary: Get latest entity check verification process by type
      description: 'Returns entity check verification for a given type.


        Required permissions:

        At least one of the following permissions is required: DataProtectionAccess, DataProtectionDashboardAccess'
      operationId: GetLatestEntityCheckVerification
      parameters:
      - name: type
        in: path
        description: Entity check verification type
        required: true
        schema:
          type: string
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. Entity check verification is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLatestEntityCheckVerificationResponseServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found. Entity check verification with given type does not exist
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    GetLatestEntityCheckVerificationResponse:
      type: object
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/EntityCheckVerificationStatus'
      additionalProperties: false
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    GetLatestEntityCheckVerificationResponseServiceResponse:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/GetLatestEntityCheckVerificationResponse'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ObjectServiceResponse:
      type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    EntityCheckVerificationStatus:
      enum:
      - InProgress
      - Complete
      - Terminated
      type: string
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
