openapi: 3.2.0
info:
  title: Fenergo Nebula Identity Scim Resource Types API
  description: '## What is SCIM?'
  version: v1
servers:
- url: /scim
security:
- Bearer: []
tags:
- name: Resource Types
paths:
  /ResourceTypes:
    get:
      tags:
      - Resource Types
      summary: Gets all the resource types
      operationId: GetAllResourceTypes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceTypesListResponseDto'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:ListResponse
                totalResults: 1
                itemsPerPage: 1
                startIndex: 1
                Resources:
                - schemas:
                  - urn:ietf:params:scim:schemas:core:2.0:ResourceType
                  id: User
                  name: User
                  description: User Schema
                  endpoint: /scim/Users
                  schema: urn:ietf:params:scim:schemas:core:2.0:User
                  schemaExtensions:
                  - schema: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
                    required: false
                  meta:
                    location: https://company.com/scim/ResourceTypes/User
                    resourceType: ResourceType
  /ResourceTypes/{id}:
    get:
      tags:
      - Resource Types
      summary: Gets a resource type by ID
      operationId: GetResourceTypeById
      parameters:
      - name: id
        in: path
        description: Id of the resource type to be retrieved.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceTypesResponseDto'
              example:
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:ResourceType
                id: User
                name: User
                description: User Schema
                endpoint: /scim/Users
                schema: urn:ietf:params:scim:schemas:core:2.0:User
                schemaExtensions:
                - schema: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
                  required: false
                meta:
                  location: https://company.com/scim/ResourceTypes/User
                  resourceType: ResourceType
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
components:
  schemas:
    ResourceTypesSchemaExtensionDto:
      type: object
      properties:
        schema:
          type:
          - string
          - 'null'
          description: 'The URI of an extended schema, e.g., "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User". <br />

            This MUST be equal to the "id" attribute of a "Schema" resource. REQUIRED'
          example: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
        required:
          type: boolean
          description: A Boolean value that specifies whether or not the schema is required for the resource type
          example: false
      additionalProperties: false
    ErrorResponseDto:
      type: object
      properties:
        schemas:
          type:
          - array
          - 'null'
          items:
            type: string
          description: 'List of one or more URIs that indicate included SCIM schemas that are used to indicate the attributes contained within a resource. <br />

            Example: [ "urn:ietf:params:scim:api:messages:2.0:Error" ]'
        status:
          type:
          - string
          - 'null'
          description: The HTTP status code of the error response
          example: '400'
        scimType:
          type:
          - string
          - 'null'
          description: The type of error
          example: invalidSyntax
        detail:
          type:
          - string
          - 'null'
          description: The summary of the error
          example: The request is not well-formatted
      additionalProperties: false
    ResourceTypesListResponseDto:
      type: object
      properties:
        schemas:
          type:
          - array
          - 'null'
          items:
            type: string
          description: 'List of one or more URIs that indicate included SCIM schemas that are used to indicate the attributes contained within a resource. <br />

            Example: [ "urn:ietf:params:scim:api:messages:2.0:ListResponse" ]'
        totalResults:
          type: integer
          description: The total number of results returned by the list or query operation
          format: int32
          example: 1
        itemsPerPage:
          type: integer
          description: The number of resources returned in a list response page
          format: int32
          example: 1
        startIndex:
          type: integer
          description: The 1-based index of the first result in the current set of list results
          format: int32
          example: 1
        Resources:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ResourceTypesResponseDto'
          description: A list of all the resource types. This MAY be a subset of the full set of resources if pagination is requested
      additionalProperties: false
    MetaDto:
      type: object
      properties:
        resourceType:
          type:
          - string
          - 'null'
          description: The name of the resource type of the resource
          example: User
        created:
          type: string
          description: The "DateTime" that the resource was added to the service provider
          format: date-time
          example: '2022-02-02T12:59:59.123456'
        lastModified:
          type: string
          description: 'The most recent "DateTime" that the details of this were updated at the service provider. <br />

            If this resource has never been modified since its initial creation, the value will be the same as the value of "created"'
          format: date-time
          example: '2022-02-02T12:59:59.123456'
        location:
          type:
          - string
          - 'null'
          description: The URI of the resource being returned
          example: https://company.com/scim/Users/12345678-1234-1234-1234-123456789011
        version:
          type: integer
          description: The version of the resource being returned
          format: int32
          example: 0
      additionalProperties: false
      description: A complex attribute containing resource metadata, assigned by the service provider
    ResourceTypesResponseDto:
      type: object
      properties:
        schemas:
          type:
          - array
          - 'null'
          items:
            type: string
          description: 'List of one or more URIs that indicate included SCIM schemas that are used to indicate the attributes contained within a resource. <br />

            Example: [ "urn:ietf:params:scim:schemas:core:2.0:ResourceType" ]'
        id:
          type:
          - string
          - 'null'
          description: The resource type's server unique id. This is often the same value as the "name" attribute
          example: User
        name:
          type:
          - string
          - 'null'
          description: The resource type name. This name is referenced by the "meta.resourceType" attribute in all resources
          example: User
        description:
          type:
          - string
          - 'null'
          description: The resource type's human-readable description
          example: User Schema
        endpoint:
          type:
          - string
          - 'null'
          description: The resource type's HTTP-addressable endpoint relative to the Base URL of the service provider, e.g., "Users"
          example: /scim/Users
        schema:
          type:
          - string
          - 'null'
          description: "The resource type's primary/base schema URI, e.g., \"urn:ietf:params:scim:schemas:core:2.0:User\". <br /> \nThis MUST be equal to the \"id\" attribute of the associated \"Schema\" resource"
          example: urn:ietf:params:scim:schemas:core:2.0:User
        schemaExtensions:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ResourceTypesSchemaExtensionDto'
          description: A list of URIs of the resource type's schema extensions
        meta:
          $ref: '#/components/schemas/MetaDto'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
