openapi: 3.2.0
info:
  title: Fenergo Nebula Business Metrics Query Projected Metrics API
  description: '**Business Metrics Query API**:


    Business Metrics Query API provides endpoints in order to retrieve all related models and their versions.


    **Business Metrics Query API provides**:'
  version: '1.0'
servers:
- url: /businessmetricsquery
security:
- Bearer: []
tags:
- name: ProjectedMetrics
paths:
  /api/projectedmetrics/getjourneyestimatesbytype:
    post:
      tags:
      - ProjectedMetrics
      summary: Get average completed journeys by type
      description: 'Required permissions:

        Following permissions are required: BusinessMetricsAccess'
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: The request containing journey type and month details
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/JourneyEstimatesByTypeRequestDtoServiceRequest'
          text/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/JourneyEstimatesByTypeRequestDtoServiceRequest'
          application/*+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/JourneyEstimatesByTypeRequestDtoServiceRequest'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/JourneyEstimatesByTypeResponseDtoIEnumerableServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyEstimatesByTypeResponseDtoIEnumerableServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/JourneyEstimatesByTypeResponseDtoIEnumerableServiceResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '500':
          description: Internal Server Error
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
      operationId: postApiProjectedmetricsGetjourneyestimatesbytype
      x-operation-id-source: derived
components:
  schemas:
    JourneyEstimatesByTypeResponseDto:
      type: object
      properties:
        tenant:
          type:
          - string
          - 'null'
        journeyType:
          type:
          - string
          - 'null'
        month:
          type:
          - string
          - 'null'
          readOnly: true
        averageCount:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    JourneyEstimatesByTypeResponseDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/JourneyEstimatesByTypeResponseDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    JourneyEstimatesByTypeRequestDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/JourneyEstimatesByTypeRequestDto'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    JourneyEstimatesByTypeRequestDto:
      type: object
      properties:
        journeyType:
          type:
          - string
          - 'null'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
