openapi: 3.2.0
info:
  title: Fenergo Nebula Doc Gen Query Datasource API
  description: '**Doc Gen Query API**:


    Doc Gen Query API retrieves Document Generation configurations.


    **Doc Gen Query API provides**:


    The ability to query for Document Generation configurations. That includes searching a document template by ID.'
  version: '1.0'
servers:
- url: /docgenquery
security:
- Bearer: []
tags:
- name: Data Source
paths:
  /api/datasource:
    get:
      tags:
      - Data Source
      summary: Get all data source configurations for tenant
      description: 'This method returns all data source configurations for a given tenant.


        Required permissions:

        Following permissions are required: DocGenConfigurationAccess'
      operationId: GetDatasources
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. The list of data sources is returned
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DatasourceDtoIEnumerableServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/DatasourceDtoIEnumerableServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/DatasourceDtoIEnumerableServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    DatasourceDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DatasourceDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    DatasourceDto:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: Name of the data source
          example: Related Products
        value:
          type:
          - string
          - 'null'
          description: Value of the data source
          example: relatedProducts
        isAssociationType:
          type: boolean
          description: Whether the item is an example of assoication type
        supportedDataSource:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DatasourceDto'
          description: Data sources that the current item can have relationships with
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ValidationErrorModelListServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ValidationErrorModel'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
      example:
        data:
        - propertyName: data
          errorMessage: Data is required
          attemptedValue: ''
          errorCode: NotNullValidator
        messages:
        - message: Data is required
          type: Error
          errorCode: Error Code
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ValidationErrorModel:
      type: object
      properties:
        propertyName:
          type:
          - string
          - 'null'
        errorMessage:
          type:
          - string
          - 'null'
        attemptedValue: {}
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
