openapi: 3.2.0
info:
  title: Fenergo Nebula Event Ingress Event Types API
  description: '## Purpose of the API


    The purpose of the Event Ingress API is to is to provide an endpoint for third party applications to send events to, which will allow Fen-X to process entity related events.


    Processing of an event will trigger the correspondent journey depending on the event type and sub type received.'
  version: '1.0'
servers:
- url: /eventingress
security:
- Bearer: []
tags:
- name: Event Types
paths:
  /v1/event-types:
    get:
      tags:
      - Event Types
      summary: List all available event types, event subtypes, and event subtypes' business…
      description: This method will return a list of allowed event types with event subtypes.
      operationId: ListEventTypes
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Success. The list of event types with event subtypes is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventTypeDtoListServiceResponse'
        '403':
          description: The service is disabled.
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
    post:
      tags:
      - Event Types
      summary: Add a new event type, event subtypes, and map event subtypes to business…
      description: This method creates a new even type and event subtypes, and maps provided event subtypes to business processes.
      operationId: AddEventType
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Fenergo.Nebula.EventIngress.Ingress.Api.V1.Models.AddEventTypeRequest class that represents add event type request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddEventTypeRequest'
      responses:
        '400':
          description: The request has missing/invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '200':
          description: The event type and event subtypes are created successfully.
        '409':
          description: The event type or subtype already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '403':
          description: The service is disabled.
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
    put:
      tags:
      - Event Types
      summary: Update an existing event type, event subtypes, and event subtypes' business…
      description: This method updates an existing even type and event subtypes.
      operationId: UpdateEventType
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Fenergo.Nebula.EventIngress.Ingress.Api.V1.Models.UpdateEventTypeRequest class that represents update event type request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventTypeRequest'
      responses:
        '400':
          description: The request has missing/invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '200':
          description: The event type and event subtypes are updated successfully.
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: The event type doesn't exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '403':
          description: The service is disabled.
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /v1/event-types/{eventType}:
    delete:
      tags:
      - Event Types
      summary: Delete an existing event type, event subtypes, and event subtypes' business…
      description: This method deletes an existing even type and event subtypes.
      operationId: DeleteEventType
      parameters:
      - name: eventType
        in: path
        description: The key of the event type to be deleted.
        required: true
        schema:
          type: string
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '400':
          description: The request has missing/invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '200':
          description: The event type and event subtypes are updated successfully.
        '404':
          description: The event type doesn't exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '403':
          description: The service is disabled.
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    UpdateEventTypeRequest:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
          description: The event type's key e.g. "externaldata"
          example: externaldata
        displayName:
          type:
          - string
          - 'null'
          description: The event type's display name e.g. "External Data"
          example: External Data
        eventSubtypes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EventSubtypeDto'
          description: Supported event subtypes
      additionalProperties: false
      description: Update Event Ingress event type request.
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    EventTypeDtoListServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EventTypeDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    AddEventTypeRequest:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
          description: The event type's key e.g. "externaldata"
          example: externaldata
        displayName:
          type:
          - string
          - 'null'
          description: The event type's display name e.g. "External Data"
          example: External Data
        eventSubtypes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EventSubtypeDto'
          description: Supported event subtypes
      additionalProperties: false
      description: Add Event Ingress event type request.
    EventTypeDto:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        displayName:
          type:
          - string
          - 'null'
        isSystemDefined:
          type: boolean
        eventSubtypes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EventSubtypeDto'
      additionalProperties: false
    EventSubtypeDto:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        displayName:
          type:
          - string
          - 'null'
        businessProcessType:
          type:
          - string
          - 'null'
      additionalProperties: false
    ValidationErrorModelListServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ValidationErrorModel'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ValidationErrorModel:
      type: object
      properties:
        propertyName:
          type:
          - string
          - 'null'
        errorMessage:
          type:
          - string
          - 'null'
        attemptedValue: {}
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
