openapi: 3.2.0
info:
  title: Fenergo Nebula Portal Tenant Query Auth0 API
  description: '**Portal Tenant Query API**:


    Portal Tenant Query API provides methods related to the Portal Users.'
  version: '4.0'
servers:
- url: /portaltenantquery
security:
- Bearer: []
tags:
- name: Auth0
paths:
  /api/auth0/passwordresetticket/{id}:
    get:
      tags:
      - Auth0
      summary: Gets password reset ticket
      description: 'Gets a password reset ticket for a given user id.


        Required permissions:

        Following permissions are required: PortalTenantUserAdmin'
      operationId: GetPasswordResetTicket
      parameters:
      - name: id
        in: path
        description: Portal user identifier for which the ticket is to be created.
        required: true
        schema:
          type: string
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__Fenergo.Nebula.Portal.Tenant.Query.Application.Dto.PasswordResetTicketDto__Fenergo.Nebula.Portal.Tenant.Query.Application__Version_4.1.0.0__Culture_neutral__PublicKeyToken_null'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.Object__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e'
              example:
                data: {}
                messages:
                - message: Not Found
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.Object__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.Object__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.String__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    Fenergo.Nebula.Portal.Tenant.Query.Application.Dto.PasswordResetTicketDto:
      type: object
      properties:
        url:
          type:
          - string
          - 'null'
          description: The URL that represents the ticket.
          example: https://portal.eu.auth0.com/u/reset-password?ticket=Mkz83N164Y5o2d9WsklH0UVlbgAi3htV#
        expirationDate:
          type:
          - string
          - 'null'
          description: The ticket's expiration date.
          example: '2022-08-02T13:50:08.2847430Z'
      additionalProperties: false
      description: Response DTO representing password reset ticket
    ? Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__Fenergo.Nebula.Portal.Tenant.Query.Application.Dto.PasswordResetTicketDto__Fenergo.Nebula.Portal.Tenant.Query.Application__Version_4.1.0.0__Culture_neutral__PublicKeyToken_null
    : type: object
      properties:
        data:
          $ref: '#/components/schemas/Fenergo.Nebula.Portal.Tenant.Query.Application.Dto.PasswordResetTicketDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ? Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.String__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e
    : type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ? Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponse_1__System.Object__System.Private.CoreLib__Version_8.0.0.0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e
    : type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
