openapi: 3.2.0
info:
  title: Fenergo Nebula Identity Scim Service Provider Config API
  description: '## What is SCIM?'
  version: v1
servers:
- url: /scim
security:
- Bearer: []
tags:
- name: Service Provider Config
paths:
  /ServiceProviderConfig:
    get:
      tags:
      - Service Provider Config
      summary: Gets the service provider config
      operationId: GetServiceProviderConfig
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceProviderConfigResponseDto'
              example:
                id: 83d4b220-ed43-41b6-8559-2a5c0b67eee3
                patch:
                  supported: true
                bulk:
                  supported: true
                  maxOperations: 100
                  maxPayloadSize: 1048576
                filter:
                  supported: true
                  maxResults: 200
                changePassword:
                  supported: false
                sort:
                  supported: false
                etag:
                  supported: false
                authenticationSchemes:
                - name: OAuth Bearer Token
                  description: Authentication scheme using the OAuth Bearer Token Standard
                  specUri: http://www.rfc-editor.org/info/rfc6750
                  type: oauthbearertoken
                  primary: true
                meta:
                  created: '0001-01-01T00:00:00'
                  lastModified: '0001-01-01T00:00:00'
                  version: 0
                  location: https://company.com/scim/ServiceProviderConfig
                schemas:
                - urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig
components:
  schemas:
    ServiceProviderConfigFilterDto:
      type: object
      properties:
        supported:
          type: boolean
          description: A Boolean value specifying whether or not the operation is supported
          example: true
        maxResults:
          type: integer
          description: An integer value specifying the maximum number of resources returned in a response
          format: int32
          example: 200
      additionalProperties: false
      description: A complex type that specifies FILTER options
    ServiceProviderConfigResponseDto:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: The unique ID of the service provider configuration
          example: 83d4b220-ed43-41b6-8559-2a5c0b67eee3
        patch:
          $ref: '#/components/schemas/ServiceProviderConfigSupportedDto'
        bulk:
          $ref: '#/components/schemas/ServiceProviderConfigBulkDto'
        filter:
          $ref: '#/components/schemas/ServiceProviderConfigFilterDto'
        changePassword:
          $ref: '#/components/schemas/ServiceProviderConfigSupportedDto'
        sort:
          $ref: '#/components/schemas/ServiceProviderConfigSupportedDto'
        etag:
          $ref: '#/components/schemas/ServiceProviderConfigSupportedDto'
        authenticationSchemes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceProviderConfigAuthenticationSchemeDto'
          description: A multi-valued complex type that specifies supported authentication scheme properties
        meta:
          $ref: '#/components/schemas/MetaDto'
        schemas:
          type:
          - array
          - 'null'
          items:
            type: string
          description: 'List of one or more URIs that indicate included SCIM schemas that are used to indicate the attributes contained within a resource. <br />

            Example: [ "urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig" ]'
      additionalProperties: false
    MetaDto:
      type: object
      properties:
        resourceType:
          type:
          - string
          - 'null'
          description: The name of the resource type of the resource
          example: User
        created:
          type: string
          description: The "DateTime" that the resource was added to the service provider
          format: date-time
          example: '2022-02-02T12:59:59.123456'
        lastModified:
          type: string
          description: 'The most recent "DateTime" that the details of this were updated at the service provider. <br />

            If this resource has never been modified since its initial creation, the value will be the same as the value of "created"'
          format: date-time
          example: '2022-02-02T12:59:59.123456'
        location:
          type:
          - string
          - 'null'
          description: The URI of the resource being returned
          example: https://company.com/scim/Users/12345678-1234-1234-1234-123456789011
        version:
          type: integer
          description: The version of the resource being returned
          format: int32
          example: 0
      additionalProperties: false
      description: A complex attribute containing resource metadata, assigned by the service provider
    ServiceProviderConfigSupportedDto:
      type: object
      properties:
        supported:
          type: boolean
          description: A Boolean value specifying whether or not the operation is supported
          example: true
      additionalProperties: false
      description: A complex type that specifies configuration options
    ServiceProviderConfigAuthenticationSchemeDto:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: The common authentication scheme name
          example: OAuth Bearer Token
        description:
          type:
          - string
          - 'null'
          description: A description of the authentication scheme
          example: Authentication scheme using the OAuth Bearer Token Standard
        specUri:
          type:
          - string
          - 'null'
          description: An HTTP-addressable URL pointing to the authentication scheme's specification
          example: http://www.rfc-editor.org/info/rfc6750
        type:
          type:
          - string
          - 'null'
          description: 'The authentication scheme. <br />

            Possible values: "oauth", "oauth2", "oauthbearertoken", "httpbasic", "httpdigest"'
          example: oauthbearertoken
        primary:
          type: boolean
          description: A Boolean value indicating the 'primary' or preferred authentication scheme
          example: true
      additionalProperties: false
      description: A complex type that specifies the supported authentication scheme properties
    ServiceProviderConfigBulkDto:
      type: object
      properties:
        supported:
          type: boolean
          description: A Boolean value specifying whether or not the operation is supported
          example: true
        maxOperations:
          type: integer
          description: An integer value specifying the maximum number of operations
          format: int32
          example: 100
        maxPayloadSize:
          type: integer
          description: An integer value specifying the maximum payload size in bytes
          format: int32
          example: 1048576
      additionalProperties: false
      description: A complex type that specifies bulk configuration options
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
