openapi: 3.2.0
info:
  title: Fenergo Nebula Dashboards Command (PENDING DEPRECATION)…
  description: '!!! IMPORTANT NOTICE:

    This API is pending deprecation and will be removed on 28.02.2026. For more information visit: https://docs.fenergox.com/notice-of-change/2025/07/22/legacy-dashboards-deprecation


    Dashboards Command API is part of FenX eco-system to manage Dashboards. All the operations require valid access token obtained from Identity service.'
  version: 1.0.0
servers:
- url: /dashboardscommand
security:
- Bearer: []
tags:
- name: User Tasks
paths:
  /api/user-tasks:
    post:
      tags:
      - User Tasks
      summary: Set task is favourite flag
      description: 'Required permissions:

        Following permissions are required: TaskDashboardAccess'
      operationId: SetIsFavouriteFlag
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetUserTasksFavouriteFlagRequestServiceRequest'
      responses:
        '202':
          description: Success. IsFavourite flag has been changed
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
  /api/user-tasks/bulk:
    post:
      tags:
      - User Tasks
      summary: Bulk set tasks is favourite flag
      description: 'Required permissions:

        Following permissions are required: TaskDashboardAccess'
      operationId: BulkSetIsFavouriteFlag
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetMultipleUserTasksFavouriteFlagRequestServiceRequest'
      responses:
        '202':
          description: Success. IsFavourite flag has been changed
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    SetMultipleUserTasksFavouriteFlagRequestServiceRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/SetMultipleUserTasksFavouriteFlagRequest'
      additionalProperties: false
      description: Service request data
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ObjectServiceResponse:
      type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    SetUserTasksFavouriteFlagRequest:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
        journeyId:
          type: string
          format: uuid
        isFavourite:
          type: boolean
        userId:
          type: string
          format: uuid
      additionalProperties: false
    SetUserTasksFavouriteFlagRequestServiceRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/SetUserTasksFavouriteFlagRequest'
      additionalProperties: false
      description: Service request data
    SetMultipleUserTasksFavouriteFlagRequest:
      type: object
      properties:
        tasks:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SetUserTasksFavouriteFlagRequest'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
