openapi: 3.2.0
info:
  title: Fenergo Nebula Reporting Query Entity Report API
  description: Reporting Query API is part of FenX eco-system to manage Reporting. All the operations require valid access token obtained from Identity service.
  version: 1.0.0
servers:
- url: /reportingquery
security:
- Bearer: []
tags:
- name: Entity Report
paths:
  /api/entity-report/entity-created-report:
    post:
      tags:
      - Entity Report
      summary: Get entities created report
      description: 'Returns the list of entities created within a specified date range.

        Limit: 10000 entities, for more, please use the /file API


        Required permissions:

        Following permissions are required: ReportingAccess'
      operationId: GetEntityCreatedReport
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Start and end date
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DateRangeReportRequestServiceRequest'
      responses:
        '200':
          description: Success. Entity report for specified criteria is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityCreatedDtoDateRangeReportResponseServiceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
  /api/entity-report/entity-created-report/file:
    post:
      tags:
      - Entity Report
      summary: Get entities created file report
      description: 'Returns the link to the file, with a list of entities created within a specified date range


        Required permissions:

        Following permissions are required: ReportingAccess'
      operationId: GetEntityCreatedFileReport
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Start and end date
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DateRangeReportFileRequestServiceRequest'
      responses:
        '200':
          description: Success. Entity report for specified criteria is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateRangeReportFileResponseServiceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
  /api/entity-report/entity-updated-report:
    post:
      tags:
      - Entity Report
      summary: Get entities updated report
      description: 'Returns the list of entities updated within a specified date range.

        Limit: 10000 entities, for more, please use the /file API


        Required permissions:

        Following permissions are required: ReportingAccess'
      operationId: GetEntityUpdatedReport
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Start and end date
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DateRangeReportRequestServiceRequest'
      responses:
        '200':
          description: Success. Entity report for specified criteria is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityUpdatedDtoDateRangeReportResponseServiceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
  /api/entity-report/entity-updated-report/file:
    post:
      tags:
      - Entity Report
      summary: Get entities updated file report
      description: 'Returns the link to the file, with a list of entities updated within a specified date range


        Required permissions:

        Following permissions are required: ReportingAccess'
      operationId: GetEntityUpdatedFileReport
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Start and end date
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DateRangeReportFileRequestServiceRequest'
      responses:
        '200':
          description: Success. Entity report for specified criteria is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateRangeReportFileResponseServiceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
components:
  schemas:
    EntityCreatedDto:
      type: object
      properties:
        createdDate:
          type: string
          description: Date the entity was created
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        legalEntityId:
          type: string
          description: Unique identifier of the entity
          format: uuid
          example: 8d631fde-505e-4101-a7cd-83ab6c054a5a
        legalEntityName:
          type:
          - string
          - 'null'
          description: Name of the entity
          example: Example Entity
        legalEntityType:
          type:
          - string
          - 'null'
          description: Type of the entity
          example: Company
        currentLegalEntityStatus:
          type:
          - string
          - 'null'
          description: Current status of the entity
          example: Client
        businessRelatedAccessLayers:
          type:
          - string
          - 'null'
          description: Business related access layers
          example: Enterprise
        geographicAccessLayers:
          type:
          - string
          - 'null'
          description: Geographic access layers
          example: Global
      additionalProperties: false
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    EntityUpdatedDto:
      type: object
      properties:
        updatedTime:
          type: string
          description: Date the entity was updated
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        eventType:
          type:
          - string
          - 'null'
          description: Name of the event that caused the entity to be updated
          example: Example Entity
        entityCreatedDate:
          type: string
          description: Date the entity was created
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        legalEntityId:
          type: string
          description: Unique identifier of the entity
          format: uuid
          example: 8d631fde-505e-4101-a7cd-83ab6c054a5a
        legalEntityName:
          type:
          - string
          - 'null'
          description: Name of the entity
          example: Example Entity
        legalEntityType:
          type:
          - string
          - 'null'
          description: Type of the entity
          example: Company
        currentLegalEntityStatus:
          type:
          - string
          - 'null'
          description: Current status of the entity
          example: Client
        entityDraftId:
          type:
          - string
          - 'null'
          description: Unique identifier of the entity draft
          format: uuid
          example: 8d631fde-505e-4101-a7cd-83ab6c054a5a
        businessRelatedAccessLayers:
          type:
          - string
          - 'null'
          description: Business related access layers
          example: Enterprise
        geographicAccessLayers:
          type:
          - string
          - 'null'
          description: Geographic access layers
          example: Global
      additionalProperties: false
    EntityUpdatedDtoDateRangeReportResponseServiceResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/EntityUpdatedDtoDateRangeReportResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DateRangeReportRequest:
      type: object
      properties:
        startDate:
          type:
          - string
          - 'null'
          description: Start Date
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        endDate:
          type:
          - string
          - 'null'
          description: End Date
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
      additionalProperties: false
      description: Request representing report
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DateRangeReportFileResponse:
      type: object
      properties:
        reportFileUrl:
          type:
          - string
          - 'null'
          description: Report File URL
          example: https://google.com/report.csv
        count:
          type: integer
          description: Count
          format: int32
          example: 23
        expirationDate:
          type: string
          description: Link expiration date
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
      additionalProperties: false
      description: Response representing file report
    EntityCreatedDtoDateRangeReportResponseServiceResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/EntityCreatedDtoDateRangeReportResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DateRangeReportRequestServiceRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DateRangeReportRequest'
      additionalProperties: false
      description: Service request data
    ObjectServiceResponse:
      type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DateRangeReportFileRequestServiceRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DateRangeReportFileRequest'
      additionalProperties: false
      description: Service request data
    DateRangeReportFileResponseServiceResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DateRangeReportFileResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    DateRangeReportFileRequest:
      type: object
      properties:
        startDate:
          type:
          - string
          - 'null'
          description: Start Date
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        endDate:
          type:
          - string
          - 'null'
          description: End Date
          format: date-time
          example: '2021-01-01T14:48:00.000Z'
        fileFormat:
          $ref: '#/components/schemas/FileFormat'
      additionalProperties: false
      description: Request representing file report
    EntityCreatedDtoDateRangeReportResponse:
      type: object
      properties:
        count:
          type: integer
          description: Count of items returned
          format: int32
          readOnly: true
          example: 22
        datasetSizeAccepted:
          type: boolean
          description: Boolean flag indicating if returned dataset size is appropriate
          readOnly: true
          example: true
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EntityCreatedDto'
          description: List of !:TDto
      additionalProperties: false
    EntityUpdatedDtoDateRangeReportResponse:
      type: object
      properties:
        count:
          type: integer
          description: Count of items returned
          format: int32
          readOnly: true
          example: 22
        datasetSizeAccepted:
          type: boolean
          description: Boolean flag indicating if returned dataset size is appropriate
          readOnly: true
          example: true
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EntityUpdatedDto'
          description: List of !:TDto
      additionalProperties: false
    FileFormat:
      enum:
      - csv
      - json
      type: string
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
