openapi: 3.2.0
info:
  title: Fenergo Nebula Narrative Command Rich Text Editor API
  description: Narrative Command API is part of FenX eco-system to manage Entity Narratives Data. All the operations require valid access token obtained from Identity service.
  version: '1.0'
servers:
- url: /narrativecommand
security:
- Bearer: []
tags:
- name: RichTextEditor
paths:
  /api/richtexteditor/{narrativeType}/{entityId}/create-url-to-upload-file:
    post:
      tags:
      - RichTextEditor
      summary: Create url to upload file.
      description: 'Creates url for file upload.


        Returns url that can be used to upload file.


        Required permissions:

        At least one of the following permissions is required: NarrativesComplianceCreate, NarrativesComplianceEdit, NarrativesBusinessCreate, NarrativesBusinessEdit'
      operationId: CreateUrlToUploadFile
      parameters:
      - name: entityId
        in: path
        description: Entity id.
        required: true
        schema:
          type: string
          format: uuid
      - name: narrativeType
        in: path
        description: Narrative Type.
        required: true
        schema:
          allOf:
          - $ref: '#/components/schemas/NarrativeType'
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Parameters to create url to upload
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateUrlToUploadFileRequestDtoServiceRequest'
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUrlToUploadFileResponseDtoServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    NarrativeType:
      enum:
      - Business
      - Compliance
      type: string
    CreateUrlToUploadFileRequestDto:
      type: object
      properties:
        narrativeId:
          type:
          - string
          - 'null'
          format: uuid
        entityId:
          type: string
          format: uuid
        fileName:
          type:
          - string
          - 'null'
        isRootContent:
          type: boolean
        contentSize:
          type: integer
          format: int64
      additionalProperties: false
    CreateUrlToUploadFileResponseDtoServiceResponse:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/CreateUrlToUploadFileResponseDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ValidationErrorModelListServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ValidationErrorModel'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
      example:
        data:
        - propertyName: data
          errorMessage: Data is required
          attemptedValue: ''
          errorCode: NotNullValidator
        messages:
        - message: Data is required
          type: Error
          errorCode: Error Code
    CreateUrlToUploadFileResponseDto:
      type: object
      properties:
        url:
          type:
          - string
          - 'null'
        fileIdentifier:
          type:
          - string
          - 'null'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    CreateUrlToUploadFileRequestDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/CreateUrlToUploadFileRequestDto'
      additionalProperties: false
    ValidationErrorModel:
      type: object
      properties:
        propertyName:
          type:
          - string
          - 'null'
        errorMessage:
          type:
          - string
          - 'null'
        attemptedValue: {}
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
