openapi: 3.2.0
info:
  title: Fenergo Nebula Digital Agents Query Outcome API
  description: '**DigitalAgents Query API**:


    DigitalAgents Query API provides methods to access data related to agents and statistics associated with their work.


    **DigitalAgents Query API provides**:


    The ability to query metrics related to digital agents work.'
  version: '1.0'
servers:
- url: /digitalagentsquery
security:
- Bearer: []
tags:
- name: Outcome
paths:
  /api/outcome:
    get:
      tags:
      - Outcome
      summary: Retrieves a list of outcomes based on the specified query parameters
      description: 'Required permissions:

        Following permissions are required: DigitalAgentsAccess'
      operationId: GetOutcomes
      parameters:
      - name: AgentExecutionId
        in: query
        description: Gets or sets the unique identifier of the agent execution.
        required: true
        schema:
          minLength: 1
          type: string
          description: Gets or sets the unique identifier of the agent execution.
      - name: AgentCategory
        in: query
        description: Gets or sets the optional category of the agent to filter outcomes by.
        schema:
          $ref: '#/components/schemas/AgentCategory'
      - name: AgentType
        in: query
        description: Gets or sets the optional type of the agent to filter outcomes by.
        schema:
          $ref: '#/components/schemas/AgentType'
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Returns the list of outcomes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutcomeDtoIEnumerableServiceResponse'
        '400':
          description: One or more validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1
                title: One or more validation errors occurred
                detail: Name is required
                status: 400
                errorCode: VALIDATION_ERROR
                validationErrors:
                - propertyName: Name
                  errorMessage: Name is required
                  attemptedValue: ''
                  validatorType: NotEmptyValidator
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3
                title: Access to resource is forbidden.
                detail: 'Access denied. Following permissions are required: Permission1, Permission2'
                status: 403
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1
                title: Internal server exception. Please, contact your provider.
                detail: null
                status: 500
                errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9
                title: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
                detail: This endpoint is obsolete and was terminated on yyyy-MM-dd
                status: 410
                errorCode: OBSOLETE_ENDPOINT
  /api/outcome/entity/{entityId}/journey/{journeyId}:
    get:
      tags:
      - Outcome
      summary: Retrieves a list of outcomes by Entity Id and Journey Id
      description: 'Required permissions:

        Following permissions are required: DigitalAgentsAccess'
      operationId: GetOutcomesByEntityIdJourneyId
      parameters:
      - name: entityId
        in: path
        description: The id of the entity
        required: true
        schema:
          type: string
          format: uuid
      - name: journeyId
        in: path
        description: The id of the journey
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Returns the list of outcomes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutcomeDtoIEnumerableServiceResponse'
        '400':
          description: One or more validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1
                title: One or more validation errors occurred
                detail: Name is required
                status: 400
                errorCode: VALIDATION_ERROR
                validationErrors:
                - propertyName: Name
                  errorMessage: Name is required
                  attemptedValue: ''
                  validatorType: NotEmptyValidator
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3
                title: Access to resource is forbidden.
                detail: 'Access denied. Following permissions are required: Permission1, Permission2'
                status: 403
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1
                title: Internal server exception. Please, contact your provider.
                detail: null
                status: 500
                errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9
                title: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
                detail: This endpoint is obsolete and was terminated on yyyy-MM-dd
                status: 410
                errorCode: OBSOLETE_ENDPOINT
  /api/outcome/journey/{journeyId}:
    get:
      tags:
      - Outcome
      summary: Retrieves a list of outcomes by Journey Id
      description: 'Required permissions:

        Following permissions are required: DigitalAgentsAccess'
      operationId: GetOutcomesByJourneyId
      parameters:
      - name: journeyId
        in: path
        description: The id of the journey
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '200':
          description: Returns the list of outcomes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutcomeDtoIEnumerableServiceResponse'
        '400':
          description: One or more validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1
                title: One or more validation errors occurred
                detail: Name is required
                status: 400
                errorCode: VALIDATION_ERROR
                validationErrors:
                - propertyName: Name
                  errorMessage: Name is required
                  attemptedValue: ''
                  validatorType: NotEmptyValidator
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3
                title: Access to resource is forbidden.
                detail: 'Access denied. Following permissions are required: Permission1, Permission2'
                status: 403
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1
                title: Internal server exception. Please, contact your provider.
                detail: null
                status: 500
                errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9
                title: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
                detail: This endpoint is obsolete and was terminated on yyyy-MM-dd
                status: 410
                errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    AgentType:
      enum:
      - IDP_Classification
      - IDP_DocSplit
      - IDP_DataExtraction
      - Task_Autocompletion
      - IDP_RelatedPartyExtraction
      - ExternalData_DataSourcing
      - SignificanceEngine_Evaluation
      - Screening_HitResolution
      - Document
      - CapacityManagement
      - ReportingAgent
      - FenAI
      - Policy
      type: string
      description: Represents the type of digital agent.
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    OutcomeDto:
      type: object
      properties:
        agentExecutionId:
          type:
          - string
          - 'null'
          description: Gets or sets the unique identifier of the agent execution.
        agentCategory:
          type:
          - string
          - 'null'
          description: Gets or sets the category of the agent that was executed.
        agentType:
          type:
          - string
          - 'null'
          description: Gets or sets the type of the agent that was executed.
        outcome:
          type:
          - string
          - 'null'
          description: Gets or sets the execution outcome result.
        entryId:
          type:
          - string
          - 'null'
          description: Gets or sets the identifier of the related entry.
        metadata:
          type:
          - object
          - 'null'
          additionalProperties:
            type: string
          description: Gets or sets the metadata associated with the outcome.
        timestamp:
          type: string
          description: Gets or sets the time stamp of the outcome.
          format: date-time
      additionalProperties: false
      description: Data Transfer Object (DTO) representing the outcome of a digital agent execution.
    AgentCategory:
      enum:
      - KYC
      - Compliance
      - Reporting
      - FenAI
      - Decisioning
      - Extraction
      - Agentic
      type: string
      description: Represents the category of an agent in the digital agents system.
    OutcomeDtoIEnumerableServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OutcomeDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
