openapi: 3.2.0
info:
  title: Fenergo Nebula Change Management Command Conflicts API
  description: '**Change Management Command API**:


    Change Management Command API provides endpoints in order to manage and configure -.


    **Change Management Command API provides**:


    Entity Change Management'
  version: '1.0'
servers:
- url: /changemanagementcommand
security:
- Bearer: []
tags:
- name: Conflicts
paths:
  /api/change-management:
    post:
      tags:
      - Conflicts
      summary: Creates a conflict
      description: 'This method creates a conflicts model.


        The method returns an object containing some basic information as the result to the user,

        and type. The returned Id can be used in the query api to get the conflicts.'
      operationId: CreateConflicts
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: The create conflicts request
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
          text/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
          application/*+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
      responses:
        '202':
          description: An instance of the Fenergo.Nebula.ChangeManagement.Common.DTO.ConflictsDto class with some metadata that represent the product created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '500':
          description: Internal server error
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/change-management/conflict/{id}:
    put:
      tags:
      - Conflicts
      summary: Update conflict
      description: Updates an existing conflict.
      operationId: UpdateConflicts
      parameters:
      - name: id
        in: path
        description: Conflict id
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      requestBody:
        description: Update conflict request.
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
          text/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
          application/*+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ConflictsDtoServiceRequest'
      responses:
        '202':
          description: Success. Conflict updated
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ConflictsDtoServiceResponse'
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '409':
          description: Conflict saving changes in expected version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: There are conflicts that cannot be resolved automatically, get latest and apply your changes
                  type: Error
                  errorCode: CONFLICT
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found. Conflict with given id does not exist
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ConflictsDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        entityId:
          type: string
          format: uuid
        taskId:
          type: string
          format: uuid
        entityConflicts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EntityConflictDto'
        managedRelationshipConflicts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ManagedRelationshipConflictDto'
        conflictingDomains:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ChangeDomain'
      additionalProperties: false
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        errorCode:
          type:
          - string
          - 'null'
      additionalProperties: false
    EntityConflictDto:
      type: object
      properties:
        existingValue:
          allOf:
          - $ref: '#/components/schemas/PropertyDto'
        newValue:
          allOf:
          - $ref: '#/components/schemas/PropertyDto'
        chosenValue:
          type:
          - string
          - 'null'
        dataKey:
          type:
          - string
          - 'null'
        friendlyName:
          type:
          - string
          - 'null'
        category:
          type:
          - string
          - 'null'
        isMaterialData:
          type: boolean
        dataColumns:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DataColumnDto'
      additionalProperties: false
    ServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    PropertyType:
      enum:
      - Single
      - Custom
      - Collection
      type: string
    DataColumnDto:
      type: object
      properties:
        dataKey:
          type:
          - string
          - 'null'
        friendlyName:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
      additionalProperties: false
    PropertyDto:
      type: object
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/PropertyType'
          readOnly: true
        discriminator:
          allOf:
          - $ref: '#/components/schemas/PropertyType'
          readOnly: true
      additionalProperties: false
    ConflictsDtoServiceResponse:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/ConflictsDto'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ObjectServiceResponse:
      type: object
      properties:
        data: {}
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
    ManagedRelationshipConflictDto:
      type: object
      properties:
        entityId:
          type: string
          format: uuid
        agentName:
          type:
          - string
          - 'null'
        dataConflicts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EntityConflictDto'
      additionalProperties: false
    ChangeDomain:
      enum:
      - Related Parties
      - Managed Relationship
      - Accounts
      - Primary Entity Data
      type: string
    ConflictsDtoServiceRequest:
      type: object
      properties:
        data:
          allOf:
          - $ref: '#/components/schemas/ConflictsDto'
      additionalProperties: false
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
