openapi: 3.2.0
info:
  title: Fenergo Nebula Data Protection Command Orphan Entity…
  description: '**Data Protection Command API**:


    Data Protection API provides both configurational and operational methods related to the client Data Protection policies. Use the Data Protection Command API to create and manage Jurisdictions. Use the Data Protection Query API to retrieve Jurisdtiction aggregates.


    **Data Protection API provides**:


    The ability to create, update and delete Data Protection Regimes.'
  version: '1.0'
servers:
- url: /dataprotectioncommand
security:
- Bearer: []
tags:
- name: OrphanEntityProcess
paths:
  /api/orphanentityprocess/{configurationId}/orphanentitycheck:
    post:
      tags:
      - OrphanEntityProcess
      summary: Trigger Orphan Entity Check
      description: 'Manually triggers orphan entity check for given configuration id


        Required permissions:

        Following permissions are required: DataProtectionCreate'
      operationId: TriggerOrphanEntityCheck
      parameters:
      - name: configurationId
        in: path
        description: Configuration id
        required: true
        schema:
          type: string
          format: uuid
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '202':
          description: Success. Orphan entity check triggered
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: Not Found. Configuration with given id does not exist
                  type: Error
                  errorCode: Error Code
        '401':
          description: User is not authorized to perform this request
          content:
            application/json:
              example:
                message: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
  /api/orphanentityprocess/deleteexpiredorphan:
    post:
      tags:
      - OrphanEntityProcess
      summary: Trigger deleting expired orphan entities process
      description: 'Manually triggers delete expired orphan entities process for given configuration id


        Required permissions:

        Following permissions are required: DataProtectionCreate'
      operationId: TriggerDeleteExpiredOrphanEntitites
      parameters:
      - name: X-TENANT-ID
        in: header
        description: The UiD of the tenant representing organization
        required: true
        schema:
          type: string
        example: b11f8be3-f29b-4959-8964-956d4af7c468
      responses:
        '202':
          description: Success. Orphan entity check triggered
        '400':
          description: Bad request. The request has missing/invalid values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorModelListServiceResponse'
        '401':
          description: Unauthorized
        '403':
          description: Access to resource is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: {}
                messages:
                - message: 'Access denied. Following permissions are required: Permission1, Permission2'
                  type: Forbidden
                  errorCode: Error Code
        '500':
          description: Internal server exception. Please, contact your provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectServiceResponse'
              example:
                data: null
                messages:
                - message: Internal server exception. Please, contact your provider.
                  type: Error
                  errorCode: INTERNAL_SERVER_ERROR
        '410':
          description: Endpoint marked as deprecated was terminated. This response will be present only if the endpoint was marked as deprecated and has reached the sunset date. During the deprecation period, the API will include additional 'sunset' and 'deprecation' headers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringServiceResponse'
              example:
                data: null
                messages:
                - message: This endpoint is obsolete and was terminated on yyyy-MM-dd
                  type: Error
                  errorCode: OBSOLETE_ENDPOINT
components:
  schemas:
    ServiceResponseMessage:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
          description: The message
          example: Success
        type:
          type:
          - string
          - 'null'
          description: 'Type of the message

            One of Info, Warning, Error, Forbidden'
          example: Info
        errorCode:
          type:
          - string
          - 'null'
          description: Error Code
          example: INTERNAL_SERVER_ERROR
      additionalProperties: false
      description: The message associated to the service response
    ObjectServiceResponse:
      type: object
      properties:
        data:
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ValidationErrorModelListServiceResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ValidationErrorModel'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
      example:
        data:
        - propertyName: data
          errorMessage: Data is required
          attemptedValue: ''
          errorCode: NotNullValidator
        messages:
        - message: Data is required
          type: Error
          errorCode: Error Code
    StringServiceResponse:
      type: object
      properties:
        data:
          type:
          - string
          - 'null'
          description: The service response DTO
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ServiceResponseMessage'
          description: List of Fenergo.Nebula.Platform.Core.Models.Response.ServiceResponseMessage associated to the service response
      additionalProperties: false
      description: Service response data
    ValidationErrorModel:
      type: object
      properties:
        propertyName:
          type:
          - string
          - 'null'
          description: Name of the property
          example: data
        errorMessage:
          type:
          - string
          - 'null'
          description: User friendly error message
          example: Data is required
        attemptedValue:
          description: Invalid value
        errorCode:
          type:
          - string
          - 'null'
          description: Internal error code
          example: NotNullValidator
      additionalProperties: false
      description: Represents the details of validation error
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
