openapi: 3.2.0
info:
  title: Profile Peer Group API
  version: 3.0.0
servers:
- url: https://api.fenergox.com/tm/profile
tags:
- name: Peer Group
paths:
  /api/v1/peer-group:
    get:
      summary: Test Get Peer Group
      description: Tests the API.
      operationId: test_get_peer_group_api_v1_peer_group_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - HTTPBearer: []
      tags:
      - Peer Group
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
